mybatis:
  mapper-locations: classpath*:mapper/*.xml  #����ӳ���ļ�
  type-aliases-package: com.wang.spring.pojo #����ʵ����
server:
  port: 8081
spring:
  datasource:
    name: andriod_arerci  #���ݿ���
    url: jdbc:mysql://localhost:3306/nice_doctor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai #url
    username: root  #�û���
    password: root  #����
    driver-class-name: com.mysql.cj.jdbc.Driver  #���ݿ���������

